#!/usr/bin/env ruby
require 'speq'
require 'speq/cli'

files = Speq::CLI.find_files(ARGV)

tests = files.map do |file|
  Speq::Test.new(&-> { instance_eval(File.read(file), file) })
end

Speq::CLI.print_report(tests)